### PR TITLE
Fix NPE due to race with a closing series

### LINKED ISSUE #2573: Panic due to NPE when processing WiredList
Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference

github.com/m3db/m3/src/x/ident.BytesID.Equal(...)
    github.com/m3db/m3/src/x/ident/bytes_id.go:46
github.com/m3db/m3/src/dbnode/storage/series.(*dbSeries).OnEvictedFromWiredList(...)
    github.com/m3db/m3/src/dbnode/storage/series/series.go:580
github.com/m3db/m3/src/dbnode/storage.(*dbShard).OnEvictedFromWiredList(...)
    github.com/m3db/m3/src/dbnode/storage/shard.go:532
github.com/m3db/m3/src/dbnode/storage/block.(*WiredList).insertAfter(...)
    github.com/m3db/m3/src/dbnode/storage/block/wired_list.go:299
github.com/m3db/m3/src/dbnode/storage/block.(*WiredList).pushBack(...)
    github.com/m3db/m3/src/dbnode/storage/block/wired_list.go:348
github.com/m3db/m3/src/dbnode/storage/block.(*WiredList).processUpdateBlock(...)
    github.com/m3db/m3/src/dbnode/storage/block/wired_list.go:239
github.com/m3db/m3/src/dbnode/storage/block.(*WiredList).Start.func1(...)
    github.com/m3db/m3/src/dbnode/storage/block/wired_list.go:169
```

~~This is a regression after an upgrade from:~~
~~b429452f1fad0533c5b3a0b20dd23d1963708203 (from v0.14.2)~~
~~to:~~
~~99477fc131a373b8d226dfd4bb42795f13c9ba0c (from v0.15.12)~~
**Update**: This bug appears to have been present for a very long time.

The stack trace indicates that the `id` in the series is nil. Judging purely from the comment block above the `id` field:
https://github.com/m3db/m3/blob/99477fc131a373b8d226dfd4bb42795f13c9ba0c/src/dbnode/storage/series/series.go#L64-L68
I'm guessing that this might be related to this commit: https://github.com/m3db/m3/commit/b4be7b1356d72a4052ecf21c6d027cad5a027b07

cc: @robskillington

### PR DESCRIPTION
**Pull request by justinjc**
Fixes #2573 by adding a `closed` flag in the series so that we don't attempt to use a nil ID when the series gets evicted from the wired list.

This adds `TestWiredListPanic` that repros #2573 after running for a long duration (30 minutes or longer).

New options were introduced to increase the frequency of ticks so that the test is more likely to hit the race condition bug.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

File: src/dbnode/storage/series/series.go [hunk 1]
```diff
@@ -592,8 +593,10 @@ func (s *dbSeries) OnEvictedFromWiredList(id ident.ID, blockStart time.Time) {
 	s.Lock()
 	defer s.Unlock()
 
-	// Should never happen
-	if !id.Equal(s.id) {
+	// If the series is closed, the ID will be nil, causing the ID equality
+	// check to panic. Further, closing the series resets the internal
+	// cached blocks, so we don't need to continue with the logic below.
+	if s.closed || !id.Equal(s.id) {
```
Comment (mway) [inline src/dbnode/storage/series/series.go:599]: Do we need `closed`? I think it might be better to do nil checks, e.g.:

```go
if id == nil || s.id == nil || !id.Equal(s.id) {
  return
}
```

Also, it's not clear whether we need to be worried about `s` itself being nil, but in that case:

```go
if s == nil || id == nil {
  return
}

s.Lock()
defer s.Unlock()

if s.id == nil || !id.Equal(s.id) {
  return
}
```

File: src/dbnode/integration/setup.go [hunk 2]
```diff
@@ -421,7 +422,8 @@ func NewTestSetup(
 			blockRetrieverMgr := block.NewDatabaseBlockRetrieverManager(
 				func(md namespace.Metadata, shardSet sharding.ShardSet) (block.DatabaseBlockRetriever, error) {
 					retrieverOpts := fs.NewBlockRetrieverOptions().
-						SetBlockLeaseManager(blockLeaseManager)
+						SetBlockLeaseManager(blockLeaseManager).
+						SetCacheBlocksOnRetrieve(true)
```
Comment (robskillington) [inline src/dbnode/integration/setup.go:426]: Hm, can we avoid setting this to `true` for all tests? 

By default we set this to false for all open source builds now so it's not really indicative of the broadly deployed set of configurations is (and would rather keep the majority of the integration tests representative of that if possible).

**Review by robskillington — APPROVED** [review]
LGTM other than minor comments

File: src/dbnode/storage/series/series.go (hunk 1 above)
Comment (justinjc) [reply src/dbnode/storage/series/series.go]: Sounds good.
