### PR TITLE
[query] Fix temporal function tag application bug

### LINKED ISSUE #2214: graphs via PromQL query on Grafana change a lot between refreshes
## General Issues

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
M3Query (M3Coordinator) Version: 0.14.2

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
Default config. One namespace (unaggregated) - retention 90d

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
Prometheus scrapes (1 min scrape interval) and writes through M3Coordinator(s) and reads are performed via dedicated M3Query (M3Coordinator)

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
Write histogram metrics with ~30 buckets (slightly higher cardinality ~20000) and try to graph in Grafana via M3Query like this:
`
histogram_quantile(0.50, sum(rate(query_latency_ms_bucket{cluster_name="$Cluster", kubernetes_namespace="$Namespace"}[5m])) by (le, $groupby))
` 

The graphs will change every time we refresh. The same query performed via prometheus (remote read) doesn't do that so looks like something to do with M3Coordinators (also Visulaization on Grafana is set to "null value - null as connected"). Attaching screenshots and see the difference between 2 refreshes:

Screen Shot 2020-03-13 at 5 45 43 PM
Screen Shot 2020-03-13 at 5 45 58 PM

### PR DESCRIPTION
**Pull request by arnikola**
Fixes #2214 

Fixes an issue where batched processing of temporal functions would sometimes cause series tag mismatches.

TODO: add regression test data for this case

### CODE REVIEW

**Comment by fingon** [comment]
Does this commit also assume some other dependencies? I cherry-picked the commit on top of 0.15rc3 and result still seems similar as bug #2214 (= spurious blips on promql, when using e.g.)


`max by (process_name)(max_over_time(procstat_memory_rss{service_id=~'$service_id'}[$__interval])) `

in Grafana, which turns to this promql on API ( unquoted for your convenience ):

`/api/v1/query_range?query=max by (process_name)(max_over_time(procstat_memory_rss{service_id=~'1003'}[15s])) &start=1585547985&end=1585551585&step=15`

For example for one of the things matching, there seems to be (still) bleed-over from other time series (from Grafana query inspector, too lazy to run promql query by hand  + search for it from json):

```
71:Array[1585551375,52244480]
72:Array[1585551390,50855936]
73:Array[1585551405,52244480]
74:Array[1585551420,3901157376]
75:Array[1585551435,3902169088]
76:Array[1585551450,52961280]
77:Array[1585551465,53080064]
78:Array[1585551480,52961280]
79:Array[1585551495,53080064]
80:Array[1585551510,3903795200]
81:Array[1585551525,55300096]
82:Array[1585551540,3904131072]
83:Array[1585551555,55300096]
84:Array[1585551570,52961280]
85:Array[1585551585,55300096]
86:Array[1585551600,52961280]
87:Array[1585551615,55300096]
88:Array[1585551630,52961280]
```

Test setup: 1 coordinator, 6 db nodes, rf=3, all with this patch + 0.15rc3.

File: src/query/block/column_test.go [hunk 1]
```diff
@@ -22,24 +22,83 @@ package block
...
 	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
 	"github.com/uber-go/tally"
 )
 
-func TestColumnBuilderInfoTypes(t *testing.T) {
-	ctx := models.NewQueryContext(context.Background(),
-		tally.NoopScope, cost.NoopChainedEnforcer(),
-		models.QueryContextOptions{})
+var ctx = models.NewQueryContext(context.Background(),
```
Comment (robskillington) [inline src/query/block/column_test.go]: super nit: Maybe make this a method? In case contexts conflict across tests?

File: src/query/functions/temporal/base.go [hunk 2]
```diff
@@ -266,12 +262,14 @@ func parallelProcess(
 			series     = iter.Current()
 			datapoints = series.Datapoints()
 			stats      = series.Stats()
+			seriesMeta = metas[i]
```
Comment (robskillington) [inline src/query/functions/temporal/base.go]: paranoia: Worth checking if within bounds at all?

File: src/query/functions/temporal/base.go [hunk 3]
```diff
@@ -184,27 +164,41 @@ type blockMeta struct {
...
-
 		mu       sync.Mutex
 		wg       sync.WaitGroup
 		multiErr xerrors.MultiError
 		idx      int
 	)
 
-	builder.PopulateColumns(len(metas))
+	meta := b.Meta()
+	builder, err := c.controller.BlockBuilder(m.queryCtx, meta, nil)
```
Comment (robskillington) [inline src/query/functions/temporal/base.go]: Ah, was sharing the builder concurrently causing issues?

Comment (arnikola) [reply src/query/functions/temporal/base.go]: Yeah finally just got the other issue where it was sharing the processor, about to put up a PR after I manage to get a good repro case for it 👍

File: src/query/functions/temporal/base.go (hunk 2 above)
Comment (arnikola) [reply src/query/functions/temporal/base.go]: Yeah, may as well just in case :+1:

**Comment by fingon** [comment]
+1 from me, after this iteration I don't see #2214 in my test cluster anymore (or #2191, but that seemed to happen more on staging cluster which I upgrade only to rc's)

File: src/dbnode/encoding/m3tsz/encoder.go [hunk 4]
```diff
@@ -302,7 +302,10 @@ func (enc *encoder) LastEncoded() (ts.Datapoint, error) {
 		return ts.Datapoint{}, errNoEncodedDatapoints
 	}
 
-	result := ts.Datapoint{Timestamp: enc.tsEncoderState.PrevTime}
+	result := ts.Datapoint{
+		Timestamp:      enc.tsEncoderState.PrevTime,
+		TimestampNanos: xtime.ToUnixNano(enc.tsEncoderState.PrevTime),
```
Comment (robskillington) [inline src/dbnode/encoding/m3tsz/encoder.go:307]: Hm, should we move to add a method called `NewDatapoint(t time.Time, v float64)` and then always add the fields ourselves?

Otherwise I think other callsites might miss this as well. 

We can change the `Timestamp` and `Value` to unexported and add methods to access them (which will likely get inlined by Go). (i.e. `Timestamp() time.Time` and `TimestampNanos() int64` and `Value() float64`

File: src/query/api/v1/handler/prometheus/native/read_common.go [hunk 5]
```diff
@@ -84,214 +82,63 @@ func read(
...
-			numSteps, numSeries)
-		if err != nil {
-			return emptyResult, err
-		}
-
-		sortedBlockList = insertResult.blocks
-		meta = meta.CombineMetadata(insertResult.meta)
+	res := <-result.ResultChan()
+	if res.Err != nil {
+		return emptyResult, res.Err
```
Comment (robskillington) [inline src/query/api/v1/handler/prometheus/native/read_common.go:87]: Hm, should we add back the `defer func() { for range resultChan {} }()` before returning here? Otherwise could see it possible to leak goroutines that are blocked tryring to publish to `resultCh`.

File: src/dbnode/encoding/m3tsz/encoder.go (hunk 4 above)
Comment (arnikola) [reply src/dbnode/encoding/m3tsz/encoder.go:307]: Yeah, I was thinking that... I think there are a lot of places this will touch though; ok to do it as a follow up?

File: src/query/functions/temporal/base.go [hunk 6]
```diff
@@ -127,47 +123,27 @@ func (c *baseNode) Process(
...
-	}
-
 	m := blockMeta{
 		end:         xtime.ToUnixNano(bounds.Start),
-		seriesMeta:  resultSeriesMeta,
+		queryCtx:    queryCtx,
 		aggDuration: xtime.UnixNano(c.op.duration),
 		stepSize:    xtime.UnixNano(bounds.StepSize),
-		steps:       steps,
+		steps:       bounds.Steps(),
```
Comment (robskillington) [inline src/query/functions/temporal/base.go:131]: Hm, any reason we're not excluding __name__ part any more? (as per prior comment `// rename series to exclude their __name__ tag as part of function processing.`)

File: src/query/api/v1/handler/prometheus/native/read_common.go (hunk 5 above)
Comment (arnikola) [reply src/query/api/v1/handler/prometheus/native/read_common.go:87]: The channel can only ever have a single value, so that's not actually necessary here

File: src/query/functions/temporal/base.go [hunk 7]
```diff
@@ -266,12 +262,15 @@ func parallelProcess(
...
 			datapoints = series.Datapoints()
 			stats      = series.Stats()
+			seriesMeta = metas[i]
 		)
 
 		if stats.Enabled {
 			decodeDuration += stats.DecodeDuration
 		}
 
+		seriesMeta.Tags = seriesMeta.Tags.WithoutName()
```
Comment (robskillington) [inline src/query/functions/temporal/base.go:272]: Perhaps add `// rename series to exclude their __name__ tag as part of function processing.` above this line for consistency with other code path and explaining why without name is called?

File: src/query/functions/temporal/base.go (hunk 6 above)
Comment (arnikola) [reply src/query/functions/temporal/base.go:131]: Still around, just moved some logic around; will readd this comment around the relevant paths :+1:

File: src/query/block/column.go [hunk 8]
```diff
@@ -237,6 +237,8 @@ func (cb ColumnBlockBuilder) PopulateColumns(size int) {
 	for i := range cb.block.columns {
 		cb.block.columns[i] = column{Values: cols[size*i : size*(i+1)]}
 	}
+
+	cb.block.seriesMeta = make([]SeriesMeta, size)
```
Comment (robskillington) [inline src/query/block/column.go:241]: Should we add test coverage that this is always size of cols now?  Seems like was just missing before?

Comment (arnikola) [reply src/query/block/column.go:241]: Yeah, luckily the new test fails without this statement :+1:
