### PR TITLE
[query] Fix time() function in binary comparisons

### LINKED ISSUE #1878: m3-query: scalar operator on timestamp yielding wrong result
> Service: `m3-query`

## Context

I'm trying to build a Grafana single-stat panel that shows the number of seconds since the last successful Prometheus configuration reload.

## Problem statement

The following query works against Prometheus:

```
time() - prometheus_config_last_reload_success_timestamp_seconds
```

At the time of writing, the result coming back is around 900 seconds.

Aganst M3, the result is negative 63.7 billion!

## Response data

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/6/api/v1/query?query=time()%20-%20prometheus_config_last_reload_success_timestamp_seconds&time=1565795507"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "application": "prometheus",
            "ec2_availability_zone": "us-east-1a",
            "instance": "REDACTED",
            "job": "prometheus:ec2-discovery"
          },
          "value": [
            1565795507,
            "-63701391334.34311"
          ],
          "values": [
            [
              1565795507,
              "-63701391334.34311"
            ]
          ]
        },
        {
          "metric": {
            "application": "prometheus",
            "ec2_availability_zone": "us-east-1b",
            "instance": "REDACTED",
            "job": "prometheus:ec2-discovery"
          },
          "value": [
            1565795507,
            "-63701391324.18791"
          ],
          "values": [
            [
              1565795507,
              "-63701391324.18791"
            ]
          ]
        },
        {
          "metric": {
            "application": "prometheus",
            "ec2_availability_zone": "us-east-1c",
            "instance": "REDACTED",
            "job": "prometheus:ec2-discovery"
          },
          "value": [
            1565795507,
            "-63701391318.88583"
          ],
          "values": [
            [
              1565795507,
              "-63701391318.88583"
            ]
          ]
        }
      ]
    }
  }
}
```

## Verification

Executing this query directly against Prometheus yields the expected outcome.

## M3 Configuration

**Placement**

```
{
    "num_shards": 32,
    "replication_factor": 3,
    "instances": [
        {
            "id": "m3-data0.domain",
            "isolation_group": "us-east-1a",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "m3-data0.domain:9000",
            "hostname": "m3-data0.domain",
            "port": 9000
        },
        {
            "id": "m3-data1.domain",
            "isolation_group": "us-east-1b",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "m3-data1.domain:9000",
            "hostname": "m3-data1.domain",
            "port": 9000
        },
        {
            "id": "m3-data2.domain",
            "isolation_group": "us-east-1c",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "m3-data2.domain:9000",
            "hostname": "m3-data2.domain",
            "port": 9000
        }
    ]
}
```

**Namespaces**

```
{
  "name": "default",
  "options": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "snapshotEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
      "retentionPeriodDuration": "792h",
      "blockSizeDuration": "3h",
      "bufferFutureDuration": "10m",
      "bufferPastDuration": "10m",
      "blockDataExpiry": true,
      "blockDataExpiryAfterNotAccessPeriodDuration": "5m"
    },
    "indexOptions": {
      "enabled": true,
      "blockSizeDuration": "6h"
    }
  }
}
{
    "namespaceName": "agg_100days_1h",
    "retentionTime": "2400h"
}
{
    "namespaceName": "agg_1year_4h",
    "retentionTime": "17520h"
}
```

### PR DESCRIPTION
**Pull request by arnikola**
**What this PR does / why we need it**:
Fixes #1878

### CODE REVIEW

File: src/query/parser/promql/types.go [hunk 1]
```diff
@@ -145,23 +144,29 @@ func newScalarOperator(
...
-	return scalar.NewScalarOp(
-		func(_ time.Time) float64 { return expr.Val },
-		scalar.ScalarType,
-		tagOpts,
-	)
+	return scalar.NewScalarOp(expr.Val, tagOpts)
+}
+
+func isTime(expr promql.Expr) bool {
+	return expr.String() == "time()"
```
Comment (robskillington) [inline src/query/parser/promql/types.go]: Hm, surely there's a better way to work out of it's a time expr?  Isn't there a type safe enum like value you can use?

Comment (arnikola) [reply src/query/parser/promql/types.go]: Not before it gets parsed unfortunately; alternatively could do some weird stuff where it attempts to edit the parent's params if you receive a `time()` function, but I think that breaks the model in a worse way than this. Figured since parsing is going to be messy and special-casey anyway it won't be a huge difference

Comment (arnikola) [reply src/query/parser/promql/types.go]: Ok actually going to refactor it to make it a little less awkward; will rely on block types rather than on prom's param types and remove that janky dependency

File: src/query/parser/promql/types.go [hunk 2]
```diff
@@ -145,23 +144,29 @@ func newScalarOperator(
...
 }
 
 // NewBinaryOperator creates a new binary operator based on the type.
 func NewBinaryOperator(expr *promql.BinaryExpr,
 	lhs, rhs parser.NodeID) (parser.Params, error) {
 	matching := promMatchingToM3(expr.VectorMatching)
+	// NB: Prometheus handles `time()` in a way that's not entirely compatible
+	// with the query engine; special handling is required here.
+	lTime, rTime := isTime(expr.LHS), isTime(expr.RHS)
+	if matching == nil {
```
Comment (robskillington) [inline src/query/parser/promql/types.go]: nit: Could we make `promMatchingToM3` return `*thing, bool` instead of using `nil` to specify it didn't convert the expr?  Just tends to be the pattern we use rather than checking whether thing is nil or not (which can lead to some people forgetting to nil check, and then nil ptr dereference).

File: src/query/parser/promql/types.go [hunk 3]
```diff
@@ -424,3 +424,29 @@ func promMatchingToM3(
 		Include:        vectorMatching.Include,
 	}
 }
+
+// Iff one of left or right is a time() function, match match one to many
+// against it, and match everything.
+func timeMatcher(left, right bool) *binary.VectorMatching {
```
Comment (robskillington) [inline src/query/parser/promql/types.go]: Similar, maybe here we make it return `(*binary.VectorMatching, bool)`?

Even if we don't use the output, still makes the top level look better:
```go
matching, ok := promMatchingToM3(expr.VectorMatching)
if !ok {
  matching, _ = timeMatcher(isTime(expr.LHS), isTime(expr.RHS))
}

```

File: src/query/block/column_test.go [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+import (
+	"context"
+	"testing"
+
+	"github.com/m3db/m3/src/query/cost"
+	"github.com/m3db/m3/src/query/models"
+	"github.com/stretchr/testify/assert"
+
+	"github.com/uber-go/tally"
```
Comment (robskillington) [inline src/query/block/column_test.go]: nit: Combine the external imports here?  (don't know why linter is clearly not working...)

i.e. this should be:
```
	"context"
	"testing"

 	"github.com/m3db/m3/src/query/cost"
	"github.com/m3db/m3/src/query/models"

	"github.com/stretchr/testify/assert"
 	"github.com/uber-go/tally"
```

File: src/query/block/information.go [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+// THE SOFTWARE.
+
+package block
+
+func (t BlockType) String() string {
+	switch t {
+	case BlockM3TSZCompressed:
+		return "M3TSZ_compressed"
```
Comment (robskillington) [inline src/query/block/information.go]: Any reason this should be upper case and rest lower?  Maybe we should make it just "compressedM3TSZ" for lower camel casing or "compressed_m3tsz" if we want to do lowercase underscore separated.

File: src/query/block/information.go [hunk 6]
```diff
@@ -0,0 +1,86 @@
+// Copyright (c) 2019 Uber Technologies, Inc.
```
Comment (robskillington) [inline src/query/block/information.go]: super nit: Rename this file `info.go` for more "Go-ish" name?

File: src/query/block/information.go [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+	case BlockWrapper:
+		return "wrapper"
+	case BlockConsolidated:
+		return "consolidated"
+	}
+
+	return "unknown"
+}
+
+type BlockInformation struct {
```
Comment (robskillington) [inline src/query/block/information.go]: Needs comment yeah? (think the exported types in this file are all missing comments)

File: src/query/block/types.go [hunk 8]
```diff
@@ -30,6 +30,19 @@ import (
...
+
+const (
+	BlockM3TSZCompressed BlockType = iota
+	BlockDecompressed
+	BlockScalar
+	BlockLazy
+	BlockTime
+	BlockContainer
+	BlockWrapper
+	BlockConsolidated
```
Comment (robskillington) [inline src/query/block/types.go]: These all needs comments yeah?

File: src/query/functions/binary/common.go [hunk 9]
```diff
@@ -107,6 +76,34 @@ func tagMap(t models.Tags) map[string]models.Tag {
 	return m
 }
 
+// Iff one of left or right is a time block, match match one to many
+// against it, and match everything.
+func defaultVectorMatcherBuilder(lhs, rhs block.Block) *VectorMatching {
```
Comment (robskillington) [inline src/query/functions/binary/common.go]: Can we just make `VectorMatching` be a non-ptr type?  Then it shouldn't panic if accidentally used without being set.

File: src/query/functions/scalar/time_test.go [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+
+package scalar
+
+import (
+	"testing"
+	"time"
+
+	"github.com/m3db/m3/src/query/block"
+
+	"github.com/m3db/m3/src/query/executor/transform"
```
Comment (robskillington) [inline src/query/functions/scalar/time_test.go]: nit: missing endline here?

File: src/query/parser/promql/types.go [hunk 11]
```diff
@@ -22,7 +22,8 @@ package promql
 
 import (
 	"fmt"
-	"time"
+
+	"github.com/m3db/m3/src/query/block"
 
 	"github.com/m3db/m3/src/query/functions"
```
Comment (robskillington) [inline src/query/parser/promql/types.go]: nit: extra new line here?

File: src/query/block/types.go [hunk 12]
```diff
@@ -167,6 +182,7 @@ func (m Metadata) String() string {
 type Builder interface {
 	AppendValue(idx int, value float64) error
 	AppendValues(idx int, values []float64) error
+	SetBlockType(blockType BlockType)
```
Comment (robskillington) [inline src/query/block/types.go]: Instead of using `SetBlockType` can we just force it to be supplied in the constructor to the builder?

Seems like people could forget otherwise rather than forcing them to supply in the constructor.

File: src/query/block/information.go (hunk 7 above)
Comment (arnikola) [reply src/query/block/information.go]: Ah fair enough; thought the general idea was functions and types have full names but variables have Go-ish names, will change it

File: src/query/functions/binary/common.go (hunk 9 above)
Comment (arnikola) [reply src/query/functions/binary/common.go]: Sure, was mostly using it for the unset case, will add a bool indicating that it's been updated

File: src/query/block/information.go (hunk 6 above)
Comment (arnikola) [reply src/query/block/information.go]: Ah fair enough; thought the general idea was functions and types have full names but variables have Go-ish names, will change it

File: src/query/block/information.go (hunk 5 above)
Comment (arnikola) [reply src/query/block/information.go]: SGTM; don't really see this used as anything other than as human-readable debug info since it's all runtime stuff so makes sense to pretty it up 👍

File: src/query/block/column_test.go (hunk 4 above)
Comment (arnikola) [reply src/query/block/column_test.go]: Haha can't say I miss the linter no longer breaking builds, but will fix it up

File: src/query/block/types.go (hunk 12 above)
Comment (arnikola) [reply src/query/block/types.go]: Discussed offline re: adding a `BuildAsType` method to `Builder` instead to make this more explicit as most usages of `Build` want default typing
