### PR TITLE
[query] Fix absent function to work correctly

### LINKED ISSUE #1847: Fix absent function
The current absent function is not correct; it should instead do a stepwise comparison and split its logic on that instead as an aggregation function.

### PR DESCRIPTION
**Pull request by arnikola**
**What this PR does / why we need it**:
Fixes #1847

### CODE REVIEW

File: src/query/block/block_test.go [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+	}
+}
+
+func CompareMeta(t *testing.T, ex, ac Metadata) {
+	expectedTags := ex.Tags.Tags
+	actualTags := ac.Tags.Tags
+	require.Equal(t, len(expectedTags), len(actualTags))
+	for i, tag := range expectedTags {
+		fmt.Println("x", string(tag.Name), ":", string(tag.Value))
+		fmt.Println("a", string(actualTags[i].Name), ":", string(actualTags[i].Value))
```
Comment (robskillington) [inline src/query/block/block_test.go]: We should probably remove these Println's now yeah?

File: src/query/functions/aggregation/absent_test.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+)
+
+func mustMakeMeta(tags ...string) block.Metadata {
+	return block.Metadata{
+		Bounds: testBound,
+		Tags:   test.MustMakeTags(tags...),
+	}
+}
+
+func mustMakeSeriesMeta(tags ...string) block.SeriesMeta {
```
Comment (robskillington) [inline src/query/functions/aggregation/absent_test.go]: Aren't these available already as test.MustMakeSeriesMeta and test.MustMakeMeta?

File: src/query/test/block.go [hunk 3]
```diff
@@ -228,3 +234,21 @@ func GenerateValuesAndBounds(
 
 	return values, bounds
 }
+
+// MustMakeTags creates tags given that the number of args is even.
+func MustMakeTags(tag ...string) models.Tags {
```
Comment (robskillington) [inline src/query/test/block.go]: Hm doesn't this already appear in `block_test.go` somewhere in this PR already?

File: src/query/functions/aggregation/absent_test.go (hunk 2 above)
Comment (arnikola) [reply src/query/functions/aggregation/absent_test.go]: Unfortunately adds a circular test dependency on `test` and `block`, is there a decent way of resolving it? Tried `block_test` package but don't think that's importable from other packages right?

File: src/query/test/block.go (hunk 3 above)
Comment (arnikola) [reply src/query/test/block.go]: Yeah managed to move it to `block` package

File: src/query/block/scalar.go [hunk 4]
```diff
@@ -28,30 +28,27 @@ import (
 )
 
 // Scalar is a block containing a single value over a certain bound
-// This represents constant values; it greatly simplifies downstream operations by
-// allowing them to treat this as a regular block, while at the same time
-// having an option to optimize by accessing the scalar value directly instead
+// This represents constant values; it greatly simplifies downstream operations
+// vy allowing them to treat this as a regular block, while at the same time
```
Comment (robskillington) [inline src/query/block/scalar.go]: nit: `vy` -> `by`

File: src/query/models/tags.go [hunk 5]
```diff
@@ -431,24 +431,69 @@ func (t Tags) Normalize() Tags {
...
+		if i != 0 {
+			sb.Write(tagSeperator)
+		}
+
+		sb.WriteString(tt.String())
 	}
 
-	return strings.Join(tags, ", ")
+	return sb.String()
+	// return strings.Join(tags, ", ")
```
Comment (robskillington) [inline src/query/models/tags.go]: Do we need to remove this perhaps?

File: src/query/models/tags.go [hunk 6]
```diff
@@ -431,24 +431,69 @@ func (t Tags) Normalize() Tags {
...
+	return true
+}
+
+var tagSeperator = []byte(", ")
+
+// String returns the string representation of the tags.
 func (t Tags) String() string {
-	tags := make([]string, len(t.Tags))
+	var sb strings.Builder
+	// tags := make([]string, len(t.Tags))
```
Comment (robskillington) [inline src/query/models/tags.go]: Also this?

File: src/query/parser/promql/parse_test.go [hunk 7]
```diff
@@ -154,6 +154,8 @@ var aggregateParseTests = []struct {
 	{"bottomk(3, up)", aggregation.BottomKType},
 	{"quantile(3, up)", aggregation.QuantileType},
 	{"count_values(\"some_name\", up)", aggregation.CountValuesType},
+
```
Comment (robskillington) [inline src/query/parser/promql/parse_test.go]: nit: Remove this endline?

File: src/query/test/block.go (hunk 3 above)
Comment (robskillington) [reply src/query/test/block.go]: Hm, can we use this method instead of redeclaring this method in `block/empty_test.go`?

Seems a private version is declared there:
```go
func mustMakeTags(tag ...string) models.Tags {
	if len(tag)%2 != 0 {
		panic("must have even tag length")
	}

 	tagLength := len(tag) / 2
	t := models.NewTags(tagLength, models.NewTagOptions())
	for i := 0; i < tagLength; i++ {
		t = t.AddTag(models.Tag{
			Name:  []byte(tag[i*2]),
			Value: []byte(tag[i*2+1]),
		})
	}

 	return t
}
```
