### PR TITLE
[query] Add support for unary expressions

### LINKED ISSUE #1619: m3query error
i meet some error:

2019-05-09T07:01:06.490Z	ERROR	unable to fetch data	{"rqID": "508a98a5-d849-4745-aef8-eb4f66246c99", "error": "promql.Walk: unhandled node type *promql.UnaryExpr, -sum(rate(container_network_transmit_bytes_total{cluster=\"SGT-eks-apse1-prod\",kubernetes_io_hostname=~\"^.*$\"}[1m]))"}

but , this sql can work well in prometheus.

### PR DESCRIPTION
**Pull request by benraskin92**
**What this PR does / why we need it**:

This PR fixes #1619. It introduces support for unary expressions -- specifically `+` and `-`. For example, this query is now supported: 

```
-sum(up)
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
Yes, this PR adds support for Prometheus unary expressions (`+` and `-`).
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

File: src/query/block/lazy.go [hunk 1]
```diff
@@ -83,12 +83,20 @@ func (it *lazyStepIter) Meta() Metadata {
...
 func (it *lazyStepIter) Current() Step {
-	c := it.it.Current()
-	tt := it.opts.TimeTransform()
+	var (
+		c        = it.it.Current()
+		tt, vt   = it.opts.TimeTransform(), it.opts.ValueTransform()
+		stepVals = c.Values()
+	)
+
+	vals := make([]float64, len(stepVals))
```
Comment (prateek) [inline src/query/block/lazy.go]: nit: could you use the `make([].., 0, ..)` formulation and append instead of directly accessing by idx.

File: src/query/block/lazy.go [hunk 2]
```diff
@@ -115,7 +123,21 @@ func (it *lazySeriesIter) Err() error               { return it.it.Err() }
 func (it *lazySeriesIter) SeriesCount() int         { return it.it.SeriesCount() }
 func (it *lazySeriesIter) SeriesMeta() []SeriesMeta { return it.it.SeriesMeta() }
 func (it *lazySeriesIter) Next() bool               { return it.it.Next() }
-func (it *lazySeriesIter) Current() Series          { return it.it.Current() }
+
+func (it *lazySeriesIter) Current() Series {
+	var (
+		c    = it.it.Current()
+		vt   = it.opts.ValueTransform()
+		vals = make([]float64, len(c.values))
```
Comment (prateek) [inline src/query/block/lazy.go]: here too

File: src/query/block/lazy.go [hunk 3]
```diff
@@ -212,19 +234,27 @@ func (s unconsolidatedStep) Values() []ts.Datapoints {
 }
 
 func (it *ucLazyStepIter) Current() UnconsolidatedStep {
-	c := it.it.Current()
-	for _, val := range c.Values() {
+	var (
+		c       = it.it.Current()
+		stepDPs = c.Values()
+		dpList  = make([]ts.Datapoints, len(stepDPs))
```
Comment (prateek) [inline src/query/block/lazy.go]: here and on line 245 too

File: src/query/block/lazy.go (hunk 1 above)
Comment (benraskin92) [reply src/query/block/lazy.go]: Isn't it more efficient to allocate the length up front (instead of capacity) and index in? Or is this a better safe than sorry situation and avoid a potential panic?

Comment (prateek) [reply src/query/block/lazy.go]: can get both by doing the other version. 

i.e. when using the version with append (below), it's not expanding the slice unless the initial alloc wasn't large enough. so you still get the benefit of the up front alloc but also the safety of not panic'ing. 
```
slice := make([]type, 0, len)
for _, v := range otherThing {
  slice = append(slice, v)
}
```

Comment (benraskin92) [reply src/query/block/lazy.go]: Ah okay, yeah that makes sense.

File: src/query/parser/promql/types.go [hunk 4]
```diff
@@ -293,6 +293,18 @@ func getBinaryOpType(opType promql.ItemType) string {
 	}
 }
 
+// GetUnaryOpType returns the M3 unary op type based on the Prom op type
```
Comment (arnikola) [inline src/query/parser/promql/types.go]: nit; full stops at end of comments

File: src/query/parser/promql/parse.go [hunk 5]
```diff
@@ -266,6 +274,19 @@ func (p *parseState) walk(node pql.Node) error {
...
 
+	case *pql.UnaryExpr:
+		err := p.walk(n.Expr)
+		if err != nil {
+			return err
+		}
+
+		unaryType, ok := GetUnaryOpType(n.Op)
+		if !ok {
+			return fmt.Errorf("only + and - operators allowed for unary expressions, received: %s", n.Op.String())
```
Comment (arnikola) [inline src/query/parser/promql/parse.go]: nit; instead, have GetUnaryOpType return a (unaryType, error) and just return this error there

File: src/query/parser/promql/types.go [hunk 6]
```diff
@@ -293,6 +293,18 @@ func getBinaryOpType(opType promql.ItemType) string {
...
+func GetUnaryOpType(opType promql.ItemType) (string, bool) {
```
Comment (arnikola) [inline src/query/parser/promql/types.go]: nit; does this need to be exported?

File: src/query/block/lazy.go [hunk 7]
```diff
@@ -212,19 +235,28 @@ func (s unconsolidatedStep) Values() []ts.Datapoints {
...
 func (it *ucLazyStepIter) Current() UnconsolidatedStep {
-	c := it.it.Current()
-	for _, val := range c.Values() {
-		for i, dp := range val.Datapoints() {
-			tt, vt := it.opts.TimeTransform(), it.opts.ValueTransform()
-			val[i].Timestamp = tt(dp.Timestamp)
-			val[i].Value = vt(dp.Value)
+	var (
+		c       = it.it.Current()
+		stepDPs = c.Values()
```
Comment (arnikola) [inline src/query/block/lazy.go]: nit; `values` reads a bit better

File: src/query/block/lazy.go [hunk 8]
```diff
@@ -250,16 +282,28 @@ func (it *ucLazySeriesIter) Err() error               { return it.it.Err() }
...
 func (it *ucLazySeriesIter) Current() UnconsolidatedSeries {
-	c := it.it.Current()
-	for _, val := range c.datapoints {
-		for i, dp := range val.Datapoints() {
-			tt, vt := it.opts.TimeTransform(), it.opts.ValueTransform()
-			val[i].Timestamp = tt(dp.Timestamp)
-			val[i].Value = vt(dp.Value)
+	var (
+		c         = it.it.Current()
+		seriesDPs = c.datapoints
```
Comment (arnikola) [inline src/query/block/lazy.go]: nit; values reads better

File: src/query/block/lazy_test.go [hunk 9]
```diff
@@ -418,3 +419,224 @@ func TestUnconsolidatedSeriesIter(t *testing.T) {
 
 	assert.Equal(t, expected, actual.Datapoints())
 }
+
+// negative value offset tests
+
```
Comment (arnikola) [inline src/query/block/lazy_test.go]: nit newline

File: src/query/parser/promql/parse.go [hunk 10]
```diff
@@ -266,6 +274,19 @@ func (p *parseState) walk(node pql.Node) error {
...
+		}
+
+		return p.addLazyTransform(0, lazy.UnaryType, unaryType)
```
Comment (arnikola) [inline src/query/parser/promql/parse.go]: This is a bit janky; I think it's better to split the functions up for now (i.e. noops if it's plus, and creates a value transform otherwise)

File: src/query/parser/promql/types.go (hunk 6 above)
Comment (benraskin92) [reply src/query/parser/promql/types.go]: Nope, good call.

File: src/query/parser/promql/types.go [hunk 11]
```diff
@@ -248,7 +248,7 @@ func NewFunctionExpr(
 		return p, true, err
 
 	default:
-		// TODO: handle other types
+		// TODO: handle other types.
```
Comment (arnikola) [inline src/query/parser/promql/types.go]: nit; can probably remove this, think we handle all types

File: src/query/parser/promql/parse_test.go [hunk 12]
```diff
@@ -76,6 +77,39 @@ func TestInvalidOffset(t *testing.T) {
 	require.Error(t, err)
 }
 
+func TestUnary(t *testing.T) {
+	q := "-up"
```
Comment (arnikola) [inline src/query/parser/promql/parse_test.go]: worth adding `+up` case? Can probably generalize this to be like

```golang
for _, q := range []string{"+up","-up"} {
....
}
```

File: src/query/block/lazy_test.go [hunk 13]
```diff
@@ -418,3 +419,224 @@ func TestUnconsolidatedSeriesIter(t *testing.T) {
...
+	assert.Equal(t, expected, actual.Values())
+	assert.Equal(t, now, actual.Time())
+}
+
+func TestUnconsolidatedSeriesIterWithNegativeValueOffset(t *testing.T) {
+	ctrl := gomock.NewController(t)
+	bb := NewMockBlock(ctrl)
+	defer ctrl.Finish()
+	offset := time.Duration(0)
```
Comment (arnikola) [inline src/query/block/lazy_test.go]: mind adding one with both transform and offset?

File: src/query/block/lazy_test.go [hunk 14]
```diff
@@ -418,3 +419,224 @@ func TestUnconsolidatedSeriesIter(t *testing.T) {
...
+	assert.Equal(t, expectedVals, actual.Values())
+	assert.Equal(t, now, actual.Time())
+}
+
+func TestSeriesIterWithNegativeValueOffset(t *testing.T) {
+	ctrl := gomock.NewController(t)
+	defer ctrl.Finish()
+	b := NewMockBlock(ctrl)
+	offset := time.Duration(0)
+	off := NewLazyBlock(b, testLazyOpts(offset, -1.0))
```
Comment (arnikola) [inline src/query/block/lazy_test.go]: nit: can do `testLazyOpts(0, -1.0)` and it'll typecast it properly

File: src/query/parser/promql/parse_test.go (hunk 12 above)
Comment (benraskin92) [reply src/query/parser/promql/parse_test.go]: `+` skips the unary op, so its just a fetch. Will add a test though.

File: src/query/block/lazy_test.go (hunk 14 above)
Comment (benraskin92) [reply src/query/block/lazy_test.go]: yeah just figured I'd be more explicit with it being a duration.

File: src/query/block/lazy.go [hunk 15]
```diff
@@ -83,12 +83,20 @@ func (it *lazyStepIter) Meta() Metadata {
...
 func (it *lazyStepIter) Current() Step {
-	c := it.it.Current()
-	tt := it.opts.TimeTransform()
+	var (
+		c        = it.it.Current()
+		tt, vt   = it.opts.TimeTransform(), it.opts.ValueTransform()
+		stepVals = c.Values()
+	)
+
+	vals := make([]float64, 0, len(stepVals))
```
Comment (prateek) [inline src/query/block/lazy.go]: longer term, instead of allocating for each `Current()` call, you can reuse a field in the struct. it'd look something like this:

```
type lazyStepIter struct {
  it   StepIter		
  opts LazyOptions
  values []float64
}

func (it *lazyStepIter) Current() Step {
var (
	c        = it.it.Current()
	tt, vt   = it.opts.TimeTransform(), it.opts.ValueTransform()
	stepVals = c.Values()
)
it.values = it.values[:0]
if cap(it.values) < len(stepVals) {
  it.values = make([]float64, 0, len(stepVals))
}
...
  return ColStep{ 
    ...
    values: it.values,
  }
}
```

note: this might cause issues if the callers of the this function are relying on the returned value from this function to be valid after multiple calls to Next()/Current(). Dunno how it's used so can't say for sure. Maybe file an issue to look into this

Comment (arnikola) [reply src/query/block/lazy.go]: If we do it this way, would make sense to move all this logic into the `Next` function so we don't have to recalculate :+1:

Comment (prateek) [reply src/query/block/lazy.go]: Yeah, Next() would definitely be the better place for it.
