### PR TITLE
[query] Fix to regexes with leading wildcard

### LINKED ISSUE #2503: M3 should act like Prometheus and not use greedy regular expressions
# Filing M3 Issues

## General Issues

we found some query using prometheus and M3's prometheus query mode returns different results. 
e.g.
```
sum by(envoy_virtual_cluster) (rate(envoy_vhost_vcluster_upstream_rq{envoy_virtual_cluster=~".*workspace.*"}[5m]))"
```
returns results for `envoy_virtual_cluster` do not include `workspace`, but for promerheus is only returns results that inclucdes `workspace`. 
Here are the snapshots from m3 and prometheus for the same query.

From M3:
Screen Shot 2020-07-30 at 8 33 54 AM

From prometheus
Screen Shot 2020-07-30 at 8 34 53 AM

By doing
```
sum by(envoy_virtual_cluster) (rate(envoy_vhost_vcluster_upstream_rq{envoy_virtual_cluster=~"[^w]*workspace.*"}[5m]))
```
can work around the issue. But to make m3's prometheus mode to be consistent with prometheus's results, we should make the regex engine for m3 should follow what Prometheus does and NOT be greedy

This issue is confirmed using v0.15.6.

### PR DESCRIPTION
**Pull request by arnikola**
**What this PR does / why we need it**:
Fixes a recently introduced bug where selector like `{foo=~".*bar"}` would be parsed as a FieldMatcher rather than a RegexMatcher as intended

Fixes #2503

### CODE REVIEW

File: src/query/storage/index_test.go [hunk 1]
```diff
@@ -122,17 +122,6 @@ func TestFetchQueryToM3Query(t *testing.T) {
...
-			name:     "regexp match dot plus -> field",
-			expected: "field(t1)",
-			matchers: models.Matchers{
-				{
-					Type:  models.MatchRegexp,
-					Name:  []byte("t1"),
-					Value: []byte(".+"),
-				},
-			},
-		},
```
Comment (robskillington) [inline src/query/storage/index_test.go:135]: don’t we want to keep this test? we still want to special case this yeah? just not if there’s other input after

Comment (arnikola) [reply src/query/storage/index_test.go]: Ah damn clumsy c/p job
