### PR TITLE
[dbnode] Allow reading/writing log entries greater than flushMaxBytes from/to commit log

### LINKED ISSUE #2139: Panic if write size exceeds db/commitlog/flushMaxBytes config
Stack trace:
```
panic: runtime error: slice bounds out of range [2479967:2479955]

goroutine 2453 [running]:
bufio.(*Writer).Write(...)
	$GOROOT/src/bufio/bufio.go:632

github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*writer).write(...)
	$GOPATH/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/writer.go:315

github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*writer).write(...)
	$GOPATH/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/writer.go:308

github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*writer).Write(...)
	$GOPATH/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/writer.go:254

github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*commitLog).write(...)
	$GOPATH/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/commit_log.go:533

created by github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*commitLog).Open
	$GOPATH/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/commit_log.go:320
```

[Here's a test](https://github.com/m3db/m3/blob/71fbb8a1fd7796ec2496af6f979f7dd8ad9c03c1/src/dbnode/persist/fs/commitlog/writer_test.go#L30) that essentially shows the above error.

The problem seems to be that `fsChunkWriter` is used as an `io.Writer`, but does not stick to the `Write` function contract that it "returns the number of bytes written from p (0 <= n <= len(p))". Instead, in addition to writing the bytes from `p`, it also writes a chunk header [here](https://github.com/m3db/m3/blob/6db9eee40098040838132d24940dd775942253a3/src/dbnode/persist/fs/commitlog/writer.go#L378). This causes the returned `n` be `len(p) + 12` instead, which causes the slice bounds out of range.

### PR DESCRIPTION
**Pull request by rishabhjain08**
**What this PR does / why we need it**:

Fixes #2139

- Resolves a bug in chunk writer which resulted bufio to skip wrong
number of bytes while trying to perform a buffered write of commit log
entry.

- Resolves an issue an commit log reader allowing commit log reader to
read chunk's greater than flush size. Chunk reader was trying to peek
data in the chunk to compute its checksum. This resulted in buffer full
error for large chunk sizes. This commit resolves this issue by loading
the chunk data into a new buffer to compute its checksum instead of
trying to peek  for data in bufio's fixed length buffer.

- Introduces unit tests to test for all the above mentioned fixes with
different filled buffer capacities to make sure chunk reader/write can
gather log entries of any size across buffers and chunks without any
error.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 1]
```diff
@@ -80,18 +83,31 @@ func (r *chunkReader) readHeader() error {
 		return err
 	}
 
-	// Verify data checksum
-	data, err := r.buffer.Peek(int(size))
+	// Setup a chunk data buffer so that chunk data can be loaded into it.
```
Comment (andrewmains12) [inline src/dbnode/persist/fs/commitlog/chunk_reader.go:86]: Good catch on this! A thought: M3DB is generally speaking pretty allocation sensitive (I can't speak to this particular code path, but you'll see all manner of pooling etc to get around allocating new byte slices). 

Since all we're doing here is checksumming, do we actually need to allocate the byte slice? Looks like we may be able to do:

File: src/dbnode/persist/fs/commitlog/commit_log_test.go [hunk 2]
```diff
@@ -113,6 +113,12 @@ func newTestOptions(
 	return opts, scope
 }
 
+func randomByteArray(len int) ([]byte) {
```
Comment (andrewmains12) [inline src/dbnode/persist/fs/commitlog/commit_log_test.go:116]: Nit: maybe better to just do a string; arbitrary bytes are harder to read in comparisons.

File: src/dbnode/persist/fs/commitlog/commit_log_test.go [hunk 3]
```diff
@@ -354,23 +360,75 @@ func TestCommitLogWrite(t *testing.T) {
...
-	// Assert writes occurred by reading the commit log
-	assertCommitLogWritesByIterating(t, commitLog, writes)
+			// Call write sync
+			writeCommitLogs(t, scope, commitLog, testCase.writes).Wait()
+
+			// Close the commit log and consequently flush
+			require.NoError(t, commitLog.Close())
+
+			// Assert writes occurred by reading the commit log
+			assertCommitLogWritesByIterating(t, commitLog, testCase.writes)
```
Comment (andrewmains12) [inline src/dbnode/persist/fs/commitlog/commit_log_test.go:429]: At a glance, doesn't look like this assert checks that the returned data is the same as what we put in--maybe worth adding that check?

File: src/dbnode/persist/fs/commitlog/writer.go [hunk 4]
```diff
@@ -379,9 +382,15 @@ func (w *fsChunkWriter) Write(p []byte) (int, error) {
 
 	// Write contents to file descriptor
 	n, err := w.fd.Write(w.buff)
+	// Count bytes successfully written from slice p
+	pBytesWritten := n - chunkHeaderLen
```
Comment (andrewmains12) [inline src/dbnode/persist/fs/commitlog/writer.go:386]: As discussed--this fix makes sense to me as well, since I think we're now correctly implementing the `Writer` interface (meaning that bufio won't choke on it). ccing @robskillington as well though, since I know it was different than your suggestion (and obviously you have a helluva lot more context on the code :) )

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 5]
```diff
@@ -80,18 +83,31 @@ func (r *chunkReader) readHeader() error {
...
+	chunkDataSize := int(size)
+	if chunkDataSize > cap(r.chunkData) {
```
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:88]: I was exploring this idea as well. But unfortunately len(p) (i.e. length of log entry) is unrelated to DataSize so if len(p) < DataSize then we would not be able to read all the chunk bytes and hence wont be able to compute checksum. 

I agree that we need something better and we need to avoid one extra layer of copying buffer that this commit has introduced. I am thinking of removing buffer io all together and going directly to fd to read data and buffer it in chunkData. This will keep the number of buffer copies same as before. What are your thoughts on this? Also can you point me to a benchmark which I can run to quantify the potential performance degradation introduced by this change.

I believe that commit logs are not read in data read/write path since they are served off of the buckets. As a result, I think we wont notice any perf degradation because of the extra layer of buffer copy introduced by this change.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 6]
```diff
@@ -80,18 +83,31 @@ func (r *chunkReader) readHeader() error {
...
+	} else {
+		//Reuse existing chunk data buffer if possible
+		r.chunkData = r.chunkData[:chunkDataSize]
+	}
+
+	// To validate checksum of chunk data all the chunk data needs to be loaded into memory at once. Chunk data size is // not bounded to the flush size so peeking chunk data in order to compute checksum may result in bufio's buffer
+	// full error. To circumnavigate this issue load the chunk data into chunk reader's buffer to compute checksum
+	// instead of trying to compute checksum off of fixed size r.buffer by peeking.
+	// See https://github.com/m3db/m3/pull/2148 for details.
+	_, err = io.ReadFull(r.buffer, r.chunkData)
```
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:99]: Yes. This has different semantics. I am loading all the chunk data in chunkData. I have made changes to other places in this code so they read data off chunkData instead of r.buffer

File: src/dbnode/persist/fs/commitlog/commit_log_test.go (hunk 3 above)
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/commit_log_test.go:429]: assertCommitLogWritesByIterating performs a full check by reading log entries using commit log reader and matching them against log entries in our test case.

File: src/dbnode/persist/fs/commitlog/commit_log_test.go (hunk 2 above)
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/commit_log_test.go:116]: Annotations are []byte and compared as such here - https://github.com/m3db/m3/blob/4842611956104b2643700ae7570f0a3cbbf2446a/src/dbnode/persist/fs/commitlog/commit_log_test.go#L168

I think if I use randomString instead of random byte array even then we will have to deal with hard to read byte array comparision.

Also generating a random string with requested number of bytes is hard because of the way characters are encoded. A character can get encoded to different number of bytes. So while its easy to generate a random string of desired number of characters its much harder to generate a random string of desired number of bytes. We will have to write a custom function to generate such a string. 

Due to these complexities, I am leaning towards using randomByteArray over random string.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:99]: Note that I have changed the way we read from buffer because we are not peeking anymore [here](https://github.com/m3db/m3/pull/2277/files#diff-907ca70d2efdead40a453b9631a7ebc3R123) and [here](https://github.com/m3db/m3/pull/2277/files#diff-907ca70d2efdead40a453b9631a7ebc3R146)

File: src/dbnode/persist/fs/commitlog/commit_log_test.go (hunk 2 above)
Comment (andrewmains12) [reply src/dbnode/persist/fs/commitlog/commit_log_test.go:116]: Fair points! Tbh what I usually do when comparing byte strings in tests is:

```
assert.Equal(t, string(w.a), string(annotation))
```
Makes the output generally much easier to read, while (afaik) still comparing the same data.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (andrewmains12) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:99]: Whoops sorry, I meant to delete this one haha--explanation makes sense, thanks!

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (andrewmains12) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:88]: Great explanation, thank you! So I think the thing to do here may just be to avoid perverse allocation situations, e.g.:

```
curBufferSize: 4
writeSize: 5 (expand)
writeSize: 6 (expand)
```

Thoughts on doubling the buffer size instead (a la most array list implementations)? I was hoping we could use some go primitives for that, but I'm not sure they're readily available (append is no good to us here, I don't think).

I think if we avoid the perverse situations we're likely 'good enough'.

[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:88]: Agreed. Double the required number of byte should be good enough to prevent reallocation several times.

File: src/dbnode/persist/fs/commitlog/commit_log_test.go (hunk 3 above)
Comment (andrewmains12) [reply src/dbnode/persist/fs/commitlog/commit_log_test.go:429]: Sg, I think I just missed it.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (justinjc) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:88]: I'm not aware of any commitlog-specific benchmarks unfortunately. Maybe it won't be that complicated to write one?

In the meantime I'll deploy to a staging environment as a sanity test (it'll be hard to verify exact performance/memory impact of this change in staging because the number of writes vary too greatly for that to be an apples to apples comparison).

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 7]
```diff
@@ -100,15 +121,16 @@ func (r *chunkReader) Read(p []byte) (int, error) {
...
-			n, err := r.buffer.Read(p[:r.remaining])
-			r.remaining -= n
-			read += n
-			if err != nil {
-				return read, err
+		if r.chunkDataRemaining > 0 {
+			chunkDataOffset := len(r.chunkData) - r.chunkDataRemaining
+			n := copy(p, r.chunkData[chunkDataOffset:])
+			if n != r.chunkDataRemaining {
+				panic("Unexpected number of bytes written from chunk data to buffer")
```
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go:130]: I will delete this panic since this is something that can be tested from unit-tests and does not need an explicit check.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 8]
```diff
@@ -125,10 +147,14 @@ func (r *chunkReader) Read(p []byte) (int, error) {
 		return read, err
 	}
 
-	n, err := r.buffer.Read(p)
-	r.remaining -= n
+	chunkDataOffset := len(r.chunkData) - r.chunkDataRemaining
+	n := copy(p, r.chunkData[chunkDataOffset:][:len(p)])
+	if n != len(p) {
+		panic("Unexpected number of bytes written from chunk data to buffer")
```
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go]: Removed.

File: src/dbnode/persist/fs/commitlog/commit_log_test.go [hunk 9]
```diff
@@ -113,6 +113,12 @@ func newTestOptions(
 	return opts, scope
 }
 
+func randomByteArray(len int) []byte {
```
[the remark this answers is not in the document]
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/commit_log_test.go:116]: Done

**Comment by rishabhjain08** [comment]
Will hold this PR off until you have a chance to review it. Thanks for reviewing.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (andrewmains12) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go]: Yeah +1

**Comment by justinjc** [comment]
Thanks for reviewing, Rob. Just FYI as an additional datapoint, we did a sanity check on correctness by deploying to a staging environment where we encountered this panic originally (with `flushMaxBytes` lowered) and everything works as expected.

**Comment by rishabhjain08** [comment]
@robskillington Did you get a chance to take a look at this PR?

**Comment by robskillington** [comment]
Taking a pass on this now

**Comment by rishabhjain08** [comment]
@robskillington Did you get a chance to review this PR.

**Comment by robskillington** [comment]
Getting back to this now.

File: src/dbnode/persist/fs/commitlog/chunk_reader.go [hunk 10]
```diff
@@ -80,18 +83,36 @@ func (r *chunkReader) readHeader() error {
...
+	chunkDataSize := int(size)
+	if chunkDataSize > cap(r.chunkData) {
+		// Increase chunkData capacity so that it can fit the new chunkData.
+		chunkDataCap := cap(r.chunkData)
+		for chunkDataCap < chunkDataSize {
+			chunkDataCap *= 2
+		}
+		r.chunkData = make([]byte, chunkDataSize, chunkDataCap)
+	} else {
+		//Reuse existing chunk data buffer if possible
```
Comment (robskillington) [inline src/dbnode/persist/fs/commitlog/chunk_reader.go:96]: nit: Add space at start and "." to this comment.
```
// Reuse existing chunk data buffer if possible.
```

File: src/dbnode/persist/fs/commitlog/writer.go (hunk 4 above)
Comment (robskillington) [reply src/dbnode/persist/fs/commitlog/writer.go:386]: Yeah that sounds good, if we've tested it and it expects as behaves now with this I'm onboard with it (and looks like it does).

File: src/dbnode/persist/fs/commitlog/chunk_reader.go (hunk 10 above)
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/chunk_reader.go]: Fixed.

File: src/dbnode/persist/fs/commitlog/writer.go (hunk 4 above)
Comment (rishabhjain08) [reply src/dbnode/persist/fs/commitlog/writer.go:386]: Yeah. This change has been unit tested and cluster tested by @justinjc
