### PR TITLE
[coordinator] Influxdb write endpoint tag copy fix

### LINKED ISSUE #2125: Panic when ingesting
m3coordinator log shows stacktrace (bit weird package names but it's built from my dev aiven branch; essentially few unrelated patches on top of commit 829d13e21d99cf46982850720693505c62178da5 ) :

```
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: panic: runtime error: index out of range
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: goroutine 24319 [running]:
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/models/strconv.QuoteSimple(...)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/models/strconv/quote.go:218
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/models.Tags.quoteIDSimple(0x1d888e0, 0xc0004f9ec0, 0xc03766b180, 0xa, 0x12, 0x10c, 0x19, 0x0, 0xc0359e7620)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/models/tags.go:171 +0x477
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/models.Tags.quotedID(0x1d888e0, 0xc0004f9ec0, 0xc03766b180, 0xa, 0x12, 0x0, 0xc040041000, 0xc0359e0000)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/models/tags.go:132 +0x462
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/models.Tags.ID(0x1d888e0, 0xc0004f9ec0, 0xc03766b180, 0xa, 0x12, 0xed5c49ee9, 0x0, 0x10)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/models/tags.go:69 +0x144
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/storage/m3.(*m3storage).Write(0xc00e1fdf50, 0x1d714c0, 0xc040041110, 0xc03fad0780, 0x1d4c840, 0xc03fad0780)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/storage/m3/storage.go:578 +0xc3
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/query/storage/fanout.(*fanoutStorage).Write(0xc00e205cc0, 0x1d714c0, 0xc040041110, 0xc03fad0780, 0xc03a9d1680, 0xc03a9d1708)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/query/storage/fanout/storage.go:414 +0x2f6
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/cmd/services/m3coordinator/ingest.(*downsamplerAndWriter).WriteBatch.func2()
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/cmd/services/m3coordinator/ingest/write.go:333 +0x18b
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: github.com/aiven/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc00f3f6310, 0xc03a9d29a0, 0x15eea125293b29db, 0xc0089d15c0, 0x255f817900)
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/x/sync/pooled_worker_pool.go:147 +0x192
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]: created by github.com/aiven/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
Jan 30 09:55:40 m3-coordinator-stats-eu-1 m3coordinator[47]:         /srv/jenkins/workspace/user-aiven-deps-f30/doc/dependencies/m3db/gopath/src/github.com/aiven/m3/src/x/sync/pooled_worker_pool.go:126 +0x66
```

this seems to occur also on low-volume test system so I could try isolating the offending data if stacktrace isn't enough.

### PR DESCRIPTION
**Pull request by fingon**
Reusing Tags objects directly over the iteration did not work.  Second
best performing option was to reuse the Tag objects within array, but
replace the Tag with the __name__ with new one.

No existing test but fixed panics in our dev env. Not tested in our prod.

Fixes #2125.

### CODE REVIEW

File: src/query/api/v1/handler/influxdb/write.go [hunk 1]
```diff
@@ -188,11 +188,26 @@ func (ii *ingestIterator) Next() bool {
...
+
 func (ii *ingestIterator) Current() (models.Tags, ts.Datapoints, xtime.Unit, []byte) {
 	if ii.pointIndex < len(ii.points) && ii.nextFieldIndex > 0 && len(ii.fields) > (ii.nextFieldIndex-1) {
 		point := ii.points[ii.pointIndex]
 		field := ii.fields[ii.nextFieldIndex-1]
-		tags := ii.tags.SetName(field.name)
+		tags := copyTagsWithNewName(ii.tags, field.name)
 
 		return tags, []ts.Datapoint{ts.Datapoint{Timestamp: point.Time(),
 			Value: field.value}}, xtime.Nanosecond, nil
```
Comment (robskillington) [inline src/query/api/v1/handler/influxdb/write.go]: Note: I missed this before, it might be worth trying to choose the most granular precision to improve the M3TSZ compression ratio.

Otherwise there could be high variability in the delta-of-delta encoding when not required (i.e. a delta-of-delta encoding 4000000 nanoseconds takes many more bits than a delta-to-delta encoding of 4 milliseconds).

You could basically divide each time unit by the nanoseconds and see which one falls within exactly each unit then choose the highest occuring one that equally divides (i.e. try seconds first, then millisecond, then so on).  If they exactly fall into a unit, then emit with that unit?

Comment (fingon) [reply src/query/api/v1/handler/influxdb/write.go]: I actually wondered about that, because we get pretty lousy M3TSZ compression ratio. That would explain it, I will address that too.

Comment (fingon) [reply src/query/api/v1/handler/influxdb/write.go]: Added it in commit, but it's only ~10% space savings in our test load (1/N scale of real thing). However, better than nothing.
