### PR TITLE
[query] Special case particular Prom matchers

### LINKED ISSUE #2424: Empty tag matchers are handled incorrectly on prometheus remote-read endpoint
Issue observed for m3query `v0.15.2` on `/api/v1/prom/remote/read`, but behaviour appears to be unchanged from `v0.14.2`. In both cases, tested against dbnodes running `v0.15.2`

When using the remote-read endpoint for prometheus, the syntax for blank labels is not consistent with what is expected for prometheus when querying for a tag not present on a series. Prometheus's internal behaviour is defined as blank labels being equivalent to absent labels, which produces certain results for exact and regex matchers, that m3 does not exhibit in its entirety. In the following table, the result of querying for a label is described for both prometheus and m3. `true` indicates results are returned, `false` that they are not. The test is easy to reproduce by using `up{job...}` and `up{garbage_label...}` on any configuration.

| matcher     | prom Label Exists | 0.15.2 Label Exists | 0.14.2 Label Exists | prom Label Not Exists | 0.15.2 Label Not Exists | 0.14.2 Label Not Exists
------------- | ----------------- | ------------------- | ------------------- | --------------------- | ----------------------- | -----------------------
up{foo=""}    | false             | false               | false               | true                  | false                   | false
up{foo!=""}   | true              | true                | true                | false                 | true                    | true
up{foo=~""}   | false             | false               | false               | true                  | false                   | false
up{foo!~""}   | true              | true                | true                | false                 | true                    | true
up{foo=~".+"} | true              | true                | true                | false                 | false                   | false
up{foo=~".*"} | true              | true                | true                | true                  | false                   | false
up{foo!~".+"} | false             | false               | false               | true                  | true                    | true
up{foo!~".*"} | false             | false               | false               | false                 | true                    | true

There is an explicit test in 0.15.2 for empty labels making their way into the cluster, for this test, there were no blank labels (`foo=""`) in the m3db that may have gotten in from before the cluster was upgraded, so this should not be relevant.

### PR DESCRIPTION
**Pull request by arnikola**
**What this PR does / why we need it**:
Fixes #2424

### CODE REVIEW

File: src/query/storage/index.go [hunk 1]
```diff
@@ -127,59 +140,129 @@ func FetchQueryToM3Query(
...
+	}
+
+	// NB: no special case for regex / not regex here.
+	isNegatedRegex := matcher.Type == models.MatchNotRegexp
+	isRegex := matcher.Type == models.MatchRegexp
+	if !isNegatedRegex && !isRegex {
+		return specialCase{}
+	}
+
+	if len(matcher.Value) != 2 && matcher.Value[0] != dot {
```
Comment (robskillington) [inline src/query/storage/index.go:198]: what do you think about the case when we have "^" and "$"?

File: src/query/storage/index.go [hunk 2]
```diff
@@ -127,59 +140,129 @@ func FetchQueryToM3Query(
...
+		return specialCase{}
+	}
+
+	if matcher.Value[1] == star {
+		if isNegatedRegex {
+			// NB: This should match no results.
+			query := idx.NewNegationQuery(idx.NewAllQuery())
```
Comment (robskillington) [inline src/query/storage/index.go:205]: Shouldn't this be a negation field query?

File: src/query/storage/index.go (hunk 1 above)
Comment (robskillington) [reply src/query/storage/index.go:198]: never mind, we sanitize at a layer above 👍

**Comment by arnikola** [comment]
> LGTM, some integration type of test would be ideal - maybe see how hard it is to put into something like https://github.com/m3db/m3/blob/master/src/query/test/compatibility/testdata/selectors.test ?

Good call :+1:
