### PR TITLE
Add regression test for and fix deadlock.

### LINKED ISSUE #2155: Adding new m3db namespace causes partial cluster OOM
This has been happening with both v0.14.2 and v0.15.0-rc0

### Most recent example:

Cluster has 18 db nodes, RF=3. It has a few namespaces setup and is taking about 200k metrics / s. As soon as new namespace is added via namespace API, 14 out of 18 nodes bootstrap the new namespace without an issue. While 4 out of 18 see the new namespace added, but do not start bootstrap. At the same time the memory and goroutine count start to sharply rise on these 4 nodes until all of them OOM and start full bootstrap. There is nothing in log files of these nodes after they see the new namespace and until the process killed.

Screenshot_2020-02-18

[m3dbnode-config.yml.zip](https://github.com/m3db/m3/files/4221125/m3dbnode-config.yml.zip)
[ns.json.zip](https://github.com/m3db/m3/files/4221126/ns.json.zip)
[placement.json.zip](https://github.com/m3db/m3/files/4221127/placement.json.zip)

### Was able to reproduce on a cluster with more than a few m3db nodes:
1. Initialize a cluster with any namespace
2. Let it ingest some data
3. Add new namespace
4. Observe bootstrap problems and OOM

### PR DESCRIPTION
**Pull request by notbdu**
**What this PR does / why we need it**:

Fixes #2155 .

**Special notes for your reviewer**:

**Does this PR introduce a user-facing and/or backwards incompatible change?**:

```release-note
NONE
```

**Does this PR require updating code package or user-facing documentation?**:

```documentation-note
NONE
```

### CODE REVIEW

File: src/dbnode/integration/dynamic_namespace_add_test.go [hunk 1]
```diff
@@ -86,11 +91,40 @@ func TestDynamicNamespaceAdd(t *testing.T) {
...
+	leaseState := block.LeaseState{}
+	for i := 0; i < 100; i++ {
+		leaseDescriptor := block.LeaseDescriptor{
+			Namespace:  ns0.ID(),
+			Shard:      uint32(0),
+			BlockStart: time.Now().Truncate(ns0.Options().RetentionOptions().BlockSize()),
+		}
+		wg.Add(2)
+		go func() {
+			wg.Done()
```
Comment (arnikola) [inline src/dbnode/integration/dynamic_namespace_add_test.go]: Should these be `Done` after the OpenLease call?

Comment (notbdu) [reply src/dbnode/integration/dynamic_namespace_add_test.go]: We just want to wait for the goroutine to bootstrap. The calls are done in a loop till the server is called. They were the original source of the deadlock.
